### ISSUE TITLE
Remove glib

### ISSUE THREAD

**Issue by nwmcsween** [ConsoleKit2/ConsoleKit2#32]
Glib itself is horribly broken software and gratuitously abstract.

**Comment by EricKoegel** [comment]
Well getting away from glib/GIO at this point would basically mean rewriting all of ConsoleKit2. You're better off waiting for systembsd to develop further and use that instead.

  I'm closing this issue since I personally want to focus on add missing functionality to ConsoleKit2 rather than extensive library porting work.
