### ISSUE TITLE
Add runtime configuration of what VT's to watch.

### ISSUE THREAD

**Issue by Ferroin** [ConsoleKit2/ConsoleKit2#40]
As of right now, ConsoleKit2 appears (feel free to correct me and close this issue if I'm wrong about this) to unconditionally watch all the VT's it thinks should exist based on MAX_NR_CONSOLES in <linux/vt.h>.  Most users don't use more than 7 VT's (6 for console login, and 1 for X), and I know nobody who uses more than 12.  Based on this, watching all 63 seems rather excessive, and prevents unused ones from being deallocated.

**Comment by EricKoegel** [comment]
Judging by the MAX_NR_CONSOLES reference you're using Linux, this should be fixed with this commit: https://github.com/ConsoleKit2/ConsoleKit2/commit/e19e2515389eeab67af78fa3e35e18c05861e589 Basically if you have a kernel built in or after 2011 we spawn a single monitor thread to watch the /sys/class/tty/tty0/active file to notify us which VT is active. 
If that's not the case let me know and we can troubleshoot it.

**Comment by Ferroin** [comment]
You're right on both counts (also, thanks for fixing the how the watching is done on Linux, my system starts up almost 2.5 seconds faster since that went in).

I've done some further digging, and it appears that it isn't ConsoleKit that is holding the tty's open and preventing them from being deallocated (which was the primary reason I opened this issue), so I'm going to go ahead and close it, and then start trying to find out what actually has them open (udev is my guess as of right now).
