### ISSUE TITLE
Issue sending suspend notification to plasma-5.5.x

### ISSUE THREAD

**Issue by dflogeras** [ConsoleKit2/ConsoleKit2#56]
I had noticed that since upgrading to CK2 / plasma desktop 5.5.0, I lost the functionality of the screen locking automatically when resuming from suspend to ram.  I filed a bug with the KDE folks, but they said the issue is a possible upstream CK2 bug.

Please see for an explanation:
https://bugs.kde.org/show_bug.cgi?id=357368

**Comment by udeved** [comment]
I can't confirm this on manjaro-kde(plasma 5.5.2)
Screen is properly locked after waking up from suspend.

**Comment by dflogeras** [comment]
Sorry for the noise, seems like a Gentoo integration bug.

In case anyone else hits this you can fix it by doing the following:

emerge -1a upower

This should replace the old power management package upower-pm-utils, which was a stopgap package the Gentoo folks created to side-step systemd a while back.  Nowadays, you can (and should) use upower directly even on non-systemd installations.  Hope this helps others struggling like I was.  You may also need to restart dbus with /etc/init.d/dbus restart, in order to get rid of the old upowerd daemon.

**Comment by rworkman** [comment]
Are you running systemd there or not? More importantly, how does plasma-5.x do the suspend? In other words, what backend actually performs it? If you don't know, that's okay, but I'm trying to figure out if whether it can work at all on a machine without systemd and *with* upower-0.99.3, and if not, what needs to change in order to fix that. Using upower-0.9.23 is not a long-term solution IMHO - it's already missing a fair amount of fix/enhancement changes to 0.99.x that are not easily backportable to 0.9.23.

**Comment by dflogeras** [comment]
Hi, no I am not running systemd, I run ck2-1.0.0, upower-0.99.2 (current stable in Gentoo).  I haven't tried 0.99.3.  I see just now that you edited your post, but I'm going to reply anyway because bits are cheap :)
