### ISSUE TITLE
Failed to let cgmanger know...

### ISSUE THREAD

**Issue by Geyup** [ConsoleKit2/ConsoleKit2#72]
Hi,

I'm running Slackware 14.2 x86_64 with ConsoleKit2-1.0.0

I noticed in my logs I see this message;

console-kit-daemon[1940]: WARNING: Failed to let cgmanager know that it can remove the cgroup when it's empty, the error was: invalid request

Does this suggest a problem, something I might be able to fix, or is this fixed in the latest 1.0.2?

I hate seeing messages if there's not a problem, nothing to fix, so I'd at least like to be able to silence it?

Thanks

**Comment by EricKoegel** [comment]
Hey, yeah I haven't looked into why it's happening. It might be because the controller is set to "all" and it might need to be for each controller individually? We can at least remove the warning since it's harmless. So pull requests happily accepted.

**Comment by Geyup** [comment]
Anything I can do to silence it in ConsoleKit2-1.0.0?

thanks for the reply...

**Comment by Geyup** [comment]
@EricKoegel 

Hi just wondering if you've been able to figure this out, had time to look into it?

Asking about pull requests, I'm assuming for someone to patch this?

Nothing here on my end I can do to this?

thanks again

**Comment by godmachine81** [comment]
I also have this same issue on Slackware 14.2 with ConsoleKit2-1.0.0 provided by Slackware official pkg.  i'm getting this particular message in my syslog:  

Jun 11 01:00:59 thinkpad console-kit-daemon[567]: WARNING: Failed to let cgmanager know that it can remove the cgroup when it's empty, the error was: invalid request

i know it is harmless, but just wondering if there would be any increase in speed/performance since by default our desktop environment uses ConsoleKit plus I have custom configured my kernel to use AutoGroup Scheduler.  I can easily ignore the message if there is nothing to be gained by allowing the cgroup to be able to be notified.

Thanks you!

Lance

**Comment by Geyup** [comment]
Late reply....

I'm just going to leave the cgmanger installed, I read it does some things in Slack and I don't feel like learning or bothering with it at the moment...
