### ISSUE TITLE
Chown cgroup to logged-in user

### ISSUE THREAD

**Issue by wulframus** [ConsoleKit2/ConsoleKit2#76]
My little fix for use unprivileged LXC containers.
[consolekit-cgroup-owner.patch.zip](https://github.com/ConsoleKit2/ConsoleKit2/files/380335/consolekit-cgroup-owner.patch.zip)

**Comment by Calrama** [comment]
That should've been dealt with by https://github.com/ConsoleKit2/ConsoleKit2/pull/61; if not, please provide reproducable steps for your problem.
Also, if you want your work to get reviewed, it might be helpful to use Github's included funcitonality for that (fork the repo + send pull request), since that requires no additional trust on the reviewer's side.

**Comment by wulframus** [comment]
Ok
